version: '3.8'

services:
  develop:
    image: lmr:develop
    build:
      context: ./
      dockerfile: Dockerfile.lmr
    deploy:
      resources:
    #Number of cpus and memory accessed limits
        limits:
          cpus: '4'
          memory: 8G
    ports:
      - "8888:8888"
    container_name: lmr
    #volumes Syntax: named_volume_name:/container/path
    volumes:
     - D:/Work_Active/Github/smartport:/home/jovyan/app
    #user: root
    #working_dir: /home/${USER}/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
      - CPL_ZIP_ENCODING=UTF-8
      - JUPYTER_ALLOW_INSECURE_WRITES=true 
      - GRASS_RENDER_FILE_READ=TRUE
      - GRASS_OVERWRITE=1
      - GRASS_FONT=sans
      - GRASS_RENDER_IMMEDIATE=cairo
      - GRASS_SKIP_MAPSET_OWNER_CHECK=1
    command: start-notebook.sh 
             --NotebookApp.notebook_dir=/home/
             --NotebookApp.token='Bartlett'
    restart: always

    #References
    #https://www.stefanproell.at/2018/08/08/jupyter-docker-stacks-with-a-custom-user/
    #https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
