#Start from a core stack version
FROM  jupyter/base-notebook:2023-01-02

LABEL authors = "Mark Bartlett"
LABEL maintainer = "bartlett <mbartlett@thewaterinstitute.org>"


COPY --chown=${NB_UID}:${NB_GID} "environment.yml" "/home/${NB_USER}/tmp/"

RUN cd "/home/${NB_USER}/tmp/" && \
    mamba env update --file environment.yml && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"


